apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-app
  labels:
    app: my-app   
spec:
  replicas: 2
  selector:
    matchLabels:
      user-app: py-app
  template:
    metadata:
      labels:
        user-app: py-app
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: nodeport-container
        image: pbadhe34/my-apps:app1
        ports:
        - containerPort: 8090
        resources:
          limits:
            cpu: 10m
            memory: 20Mi
          requests:
            cpu: 10m
            memory: 20Mi
